**Usando o markdown**

Markdown são usados para comentários e enunciados. Pesquise na web como usá-los

In [2]:
# iniciando com python
# https://www.facom.ufu.br/~wendelmelo/meu_material/introducao_programacao_python_wendel_melo.pdf

x = 2 +3
a = 1
print(x)
print(a)

5
1


https://www.facom.ufu.br/~wendelmelo/pythontw201901/aula_numpy.txt

numerical python
o propósito do numpy é facilitar computação numérica, científica e matricial

Numpy disponibiliza duas classes principais:
array: array de qualquer dimensão
matrix: representa matrizes de duas dimensões (linhas e colunas)

Instalar o pacote (shell):
pip3 install -U numpy

import numpy as np
A = np.matrix(  [ [1,2], [3,4]  ]    )


In [3]:
import numpy as np
A = np.matrix(  [ [1,2 ,3 ,4 ], [5,6,7,8],[ 9,10,11,12]  ] )   
A

matrix([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [4]:
#a variável A aponta para uma matriz de duas linhas e duas colunas
type(A)


numpy.matrix

In [4]:
#acessando um elemento da matriz
print("Matrix")
print(A)
print("Acessos")
print(A[0, 1])#acessa o elemento na linha 0 e na coluna 1
print(A[1]) #acessa a linha 1 da matriz
print(A[1,:]) #acessa a linha 1 da matriz. Dois pontos significa "todas" - se na primeira dimensão, todas as linhas
print(A[:, 0])  #acessa toda a coluna 0 da matriz. Dois pontos significa "todas" - se na primeira dimensão, todas as linhas



Matrix
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Acessos
2
[[5 6 7 8]]
[[5 6 7 8]]
[[1]
 [5]
 [9]]


In [5]:
#acessando um elemento da matriz com : (python slice) ==> inicio:fim:passo
# doc completa: https://docs.python.org/3/library/stdtypes.html#typesseq
# se início é omitido, fica com a coluna 0. Ex: :1:1
# se fim é omitido, vai até o final da dimensão. Ex 1::1
# se o passo é omitido, é assumido valor 1. Ex: 1:2
print("Matrix")
print(A)
print("Acesso [0:2,1]")
print(A[0:2, 1])#acessa o elemento na linha 0 até a linha 1 (ou seja, 2-1 = 1) e na coluna 1
print("Acessos [0:2,1:4:2]")
print(A[0:2, 1:4:2])#acessa o elemento na linha 0 até a linha 1 (ou seja, 2-1 = 1) e iniciando na coluna 1, pulando uma coluna  e indo até a colune 4-1=3
print("Mostrando a matriz com as linhas reversas")
print(A[::-1,:]) 



Matrix
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Acesso [0:2,1]
[[2]
 [6]]
Acessos [0:2,1:4:2]
[[2 4]
 [6 8]]
Mostrando a matriz com as linhas reversas
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [6]:

#a função zeros gera um array de zeros
Z = np.zeros(  (4,5)    )
Z


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
#podemos gerar matrizes de números aleatórios
import numpy.random as npr
N = np.matrix(   npr.randint(-10, 10, (3, 2)  )    )  #gera matriz de numeros inteiros aleatorios entre -10 e 10, tendo 3 linhas e 2 colunas
N

matrix([[-10,   5],
        [ -3,  -6],
        [ -8,  -8]])

In [8]:
#gernado outra matriz
N = np.matrix(   npr.randint(-10, 10, (3, 2)  )    )  #gera matriz de numeros inteiros aleatorios entre -10 e 10, tendo 3 linhas e 2 colunas
N


matrix([[ 0,  1],
        [-8,  8],
        [-7,  1]])

In [9]:
# Lembre que python é orientado a objetos. Assim uma simples atribuições entre duas matrizes faz com que abas apontem para o mesmo objeto
B=A
print(A)
print(B)

print("Mudando o valor de A - veja que B foi modificado também")
A[0,0] = -100
print(A)
print(B)

print("Mudando o valor de B - veja que A foi modificado também")
B[0,0] = 30
print(A)
print(B)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Mudando o valor de A - veja que B foi modificado também
[[-100    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]
[[-100    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]
Mudando o valor de B - veja que A foi modificado também
[[30  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[30  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
# podemos criar uma matriz copiando de uma outra matriz,
C = np.matrix(A)
print(A)
print(C)
print("Mudando o valor de A - veja que C não será afetada")
A[0,0] = 50;
print(A)
print(C)


print("Mudando o valor de C - veja que A não será afetada")
C[0,0] = 100;
print(A)
print(C)

[[30  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[30  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Mudando o valor de A - veja que C não será afetada
[[50  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[30  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Mudando o valor de C - veja que A não será afetada
[[50  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [11]:
#podemos operar com blocos de matrizes
M = np.matrix(Z)
print("Matriz M: ")
print(M)
print("Matriz N: ")
print(N)
#M[ 0:3,  2:4  ] = N
M[ 0:3,  0:3:2  ] = N
print("Matriz M após a atribuição em bloco: da linha zero até a linha 3, da coluna 2 até a 4 ")
print(M)

Matriz M: 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Matriz N: 
[[ 0  1]
 [-8  8]
 [-7  1]]
Matriz M após a atribuição em bloco: da linha zero até a linha 3, da coluna 2 até a 4 
[[ 0.  0.  1.  0.  0.]
 [-8.  0.  8.  0.  0.]
 [-7.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [12]:
#podemos fazer operações diversas com matrizes
#criando uma matriz identidade (coluna com diagonal igual a 1)
B = np.matrix(   np.eye(2,2)    )
print(B)
print(np.matrix(   np.eye(10,10)    ))



[[1. 0.]
 [0. 1.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [13]:
A = np.matrix([[1 ,1], [2 ,3]])
print(A)
print(B)
#multiplicando a matriz B por um escalar
B = 4*B
B



[[1 1]
 [2 3]]
[[1. 0.]
 [0. 1.]]


matrix([[4., 0.],
        [0., 4.]])

In [14]:
#somando matrizes
print(A)
print(B)

C =  A + B
C


[[1 1]
 [2 3]]
[[4. 0.]
 [0. 4.]]


matrix([[5., 1.],
        [2., 7.]])

In [15]:
#multiplicando matrizes

print(A)
print(B)

D = A * B
D


[[1 1]
 [2 3]]
[[4. 0.]
 [0. 4.]]


matrix([[ 4.,  4.],
        [ 8., 12.]])

In [16]:
#podemos calcular potencia de matrizes

print(A)
print(B)

E = A**2 #equivale a E = A * A (multiplica a matriz por ela mesma)
E


[[1 1]
 [2 3]]
[[4. 0.]
 [0. 4.]]


matrix([[ 3,  4],
        [ 8, 11]])

In [17]:
#podemos calcular a inversa de uma matriz

print(A)
Ainversa = A**-1
print(Ainversa)
print(A * Ainversa)


[[1 1]
 [2 3]]
[[ 3. -1.]
 [-2.  1.]]
[[1. 0.]
 [0. 1.]]


In [18]:
#podemos calcular a matriz transposta
A
print(A)
print(np.transpose(A))


[[1 1]
 [2 3]]
[[1 2]
 [1 3]]


In [19]:
#a função trace que calcula o traço da matriz (a soma dos elementos da diagonal principal)

print(A)
np.trace(A)


[[1 1]
 [2 3]]


4

In [20]:
#podemos concatenar matrizes
#por coluna: hstack

print(A)
print(B)
np.hstack( (A, B) )


[[1 1]
 [2 3]]
[[4. 0.]
 [0. 4.]]


matrix([[1., 1., 4., 0.],
        [2., 3., 0., 4.]])

In [21]:
#concatenando por linhas (vertical): vstack

print(A)
print(B)
np.vstack(  (A,B)   )


[[1 1]
 [2 3]]
[[4. 0.]
 [0. 4.]]


matrix([[1., 1.],
        [2., 3.],
        [4., 0.],
        [0., 4.]])

In [22]:
#existem funções que se aplicam a todos os elementos de uma matriz

print(A)

np.sqrt(A)


[[1 1]
 [2 3]]


matrix([[1.        , 1.        ],
        [1.41421356, 1.73205081]])